In [ ]:
import torch
torch.__version__

'2.4.1+cu121'

In [ ]:
x = torch.tensor([[1.0,2.0,3.0],[1,2,3]], dtype=torch.int16)

In [ ]:
print(x[1][2])
x[0][1]


tensor(3, dtype=torch.int16)


tensor(2, dtype=torch.int16)

In [ ]:
y = torch.tensor([[1,]])
y.item()

1

In [ ]:
torch.ones([2,2,2], dtype= torch.int16)

tensor([[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]], dtype=torch.int16)

In [ ]:
y = torch.tensor([[0,0,0,],[1,2,3]],dtype= torch.float32, requires_grad=True)
out = y.pow(2).sum()
out.backward()
print(x.grad)
y.is_complex()
cpu = y.device

None


In [ ]:
float_tensor = torch.ones(1, dtype=torch.float)
double_tensor = torch.ones(1, dtype=torch.double)
complex_float_tensor = torch.ones(1, dtype=torch.complex64)
complex_double_tensor = torch.ones(1, dtype=torch.complex128)
int_tensor = torch.ones(1, dtype=torch.int)
long_tensor = torch.ones(1, dtype=torch.long)
uint_tensor = torch.ones(1, dtype=torch.uint8)
double_tensor = torch.ones(1, dtype=torch.double)
bool_tensor = torch.ones(1, dtype=torch.bool)
long_zerodim = torch.tensor(1, dtype=torch.long)
int_zerodim = torch.tensor(1, dtype=torch.int)

In [ ]:
torch.add(5, 5).dtype
(int_tensor + 5).dtype
(int_tensor + long_zerodim).dtype
(long_tensor + int_tensor).dtype
(bool_tensor + long_tensor).dtype
(bool_tensor + uint_tensor).dtype
(float_tensor + double_tensor).dtype
(complex_float_tensor + complex_double_tensor).dtype
(bool_tensor + int_tensor).dtype
torch.add(long_tensor, float_tensor).dtype

torch.float32

In [ ]:
torch.add(5,5).dtype

torch.int64

In [ ]:
(int_tensor + 5).dtype

torch.int32

In [ ]:
a = torch.randn((2,2), device = cpu)

In [ ]:
torch.device(1)

device(type='cuda', index=1)

In [ ]:
torch.layout

torch.layout

In [ ]:

a.stride()

(2, 1)

In [ ]:
a

tensor([[ 1.4822,  0.3371],
        [-0.3927, -1.1898]])

In [ ]:
torch.tensor

<function torch._VariableFunctionsClass.tensor>

In [ ]:
x = torch.randn(5, requires_grad=True)
y = x.pow(2)
print(x.equal(y.grad_fn._saved_self))  # True
print(x is y.grad_fn._saved_self)  # True

True
True


In [ ]:
x = torch.empty(1,3,1)
y = torch.empty(3,1,7)
(x+y).size()

torch.Size([3, 3, 7])

In [ ]:
a = torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
a.size()

torch.Size([2, 3])

In [ ]:
torch.pow(a,2)

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [ ]:
b = torch.arange(1,8)
b

tensor([1, 2, 3, 4, 5, 6, 7])

In [ ]:
exp = torch.arange(1,8)
exp

tensor([1, 2, 3, 4, 5, 6, 7])

In [ ]:
torch.pow(b,exp)

tensor([     1,      4,     27,    256,   3125,  46656, 823543])

In [ ]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.arange(1,5)

tensor([1, 2, 3, 4])

In [ ]:
torch.range(1,5)

<ipython-input-46-dd75ec3a47fe>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,5)


tensor([1., 2., 3., 4., 5.])

In [ ]:
torch.linspace(1,5,steps=5)

tensor([1., 2., 3., 4., 5.])

In [ ]:
torch.logspace(1,5,steps=5)

tensor([1.0000e+01, 1.0000e+02, 1.0000e+03, 1.0000e+04, 1.0000e+05])

In [ ]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [ ]:
torch.empty(2,3)

tensor([[-9.2884e+23,  3.1022e-41, -9.2871e+23],
        [ 3.1022e-41,  0.0000e+00,  0.0000e+00]])

In [ ]:
torch.empty_strided((2,3),(1,2))

tensor([[-9.2735e+23, -9.2886e+23,  0.0000e+00],
        [ 3.1022e-41,  3.1022e-41,  0.0000e+00]])

In [ ]:
c = torch.zeros_like(input = y)
c

tensor([[[0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.]]])

In [ ]:
torch.rand(2,3)

tensor([[0.8635, 0.2739, 0.4877],
        [0.3371, 0.5949, 0.9276]])

In [ ]:
torch.randn(2,3)

tensor([[-1.1213,  0.2131, -0.5757],
        [ 0.7409,  0.3439,  2.3522]])

In [ ]:
a = torch.tensor([[1,2,3],[4,5,6]])
a + 10

tensor([[11, 12, 13],
        [14, 15, 16]])

In [ ]:
a *10

tensor([[10, 20, 30],
        [40, 50, 60]])

In [ ]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.multiply(a, 10)

tensor([[10, 20, 30],
        [40, 50, 60]])

In [ ]:
t1 = torch.randn(2,3)
t2 = torch.randn(3)
torch.matmul(t1,t2).ndim
torch.matmul(t1,t2).size()

torch.Size([2])

In [ ]:
t1.ndim

1

In [ ]:
t2.size()

torch.Size([3])

In [ ]:
t1 = torch.ones(10,3,4)
t2 = torch.ones(4)
torch.matmul(t1,t2)

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])

In [ ]:
t1

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
t2

tensor([1., 1., 1., 1.])

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)
tensor_B = tensor_B.T

torch.mm(tensor_A, tensor_B) # (this will error)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
linear = torch.nn.Linear(in_features=2,
                                    out_features=5)
x = tensor_A
output = linear(x)

In [ ]:
output.shape

torch.Size([3, 5])

In [ ]:
x.shape

torch.Size([3, 2])

In [ ]:
output

tensor([[ 0.5703, -0.8396,  0.6325, -0.5534,  0.7129],
        [ 1.7603, -1.3929,  1.4171, -1.7109,  2.2879],
        [ 2.9503, -1.9461,  2.2017, -2.8684,  3.8628]],
       grad_fn=<AddmmBackward0>)

In [ ]:
x = torch.arange(0,100,10)
x.type(dtype = torch.float)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min()

tensor(0)

In [ ]:
x.max()

tensor(90)

In [ ]:
x.type(dtype = torch.float).mean()

tensor(45.)

In [ ]:
x.sum()

tensor(450)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x = torch.arange(1.,8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_re = x.reshape(1,7)
x_re, x_re.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
m = torch.ones(3,2)
n = m.t()
n, n.shape

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([2, 3]))

In [ ]:
n.view(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
n.shape

torch.Size([2, 3])

In [ ]:
n.reshape(6)

tensor([1., 1., 1., 1., 1., 1.])

In [ ]:
t1 = torch.ones(4,5)
t1.shape

torch.Size([4, 5])

In [ ]:
t1.reshape(20)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.])

In [ ]:
t1.shape

torch.Size([4, 5])

In [ ]:
x = torch.arange(1,9)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x_stack = torch.stack([x,x,x,x], dim = 1)
x_stack

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8]])

In [ ]:
x_reshape = x.reshape(1,8)
x_reshape

tensor([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
x_squeeze = x_reshape.squeeze()
x_squeeze

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x_unsqueeze = x_squeeze.unsqueeze(dim = 0)
x_unsqueeze

tensor([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
# changing the axes of the tensor or the order of dimension in the tensor

x_org = torch.rand(224,224,3)
x_permuted = x_org.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x =x.reshape(1,3,3)

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0][1][2]

tensor(6)

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[:,1]

tensor([[4, 5, 6]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[0,0,:], x[0,1,:], x[0,2,:]

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [ ]:
x[:,:,0]

tensor([[1, 4, 7]])